# This configuration simply enables mixed scoring mode

# Specific for mixed results
resultsfileordir: mixedresults

mixedmode: true # If true, create scorecard that uses results from two versions of the same test suite
